[[pages]]
path = "app.py"
name = "Home"

[[pages]]
path = "pages/Overview.py"
name = "Overview"

[[pages]]
path = "pages/Household_Actions.py"
name = "Household Models"

[[pages]]
path = "pages/Current_Power.py"
name = "Current Tokyo Power"